<option value="3">AFGHANISTAN</option>
<option value="6">ALBANIA</option>
<option value="15">ALGERIA</option>
<option value="80">AMERICAN SAMOA</option>
<option value="81">ANDORRA</option>
<option value="82">ANGOLA</option>
<option value="83">ANGUILLA, UNITED KINGDOM</option>
<option value="84">Antigua and Barbuda</option>
<option value="5">ARGENTINA</option>
<option value="118">ARMENIA</option>
<option value="85">ARUBA, NETHERLANDS</option>
<option value="86">AUSTRALIA</option>
<option value="7">AUSTRIA</option>
<option value="8">AZERBAIJAN</option>
<option value="87">BAHAMA ISLANDS</option>
<option value="9">BAHRAIN</option>
<option value="10">BANGLADESH</option>
<option value="88">BARBADOS</option>
<option value="11">BELARUS</option>
<option value="89">BELGIUM</option>
<option value="90">BELIZE</option>
<option value="91">BENIN</option>
<option value="92">BERMUDA, UNITED KINGDOM</option>
<option value="94">BHUTAN</option>
<option value="96">BOLIVIA</option>
<option value="13">BOSNIA AND HERZEGOVINA</option>
<option value="97">BOTSWANA</option>
<option value="98">BRAZIL</option>
<option value="99">BRUNEI</option>
<option value="14">BULGARIA</option>
<option value="100">BURKINA FASO</option>
<option value="101">BURUNDI</option>
<option value="155">CAMBODIA</option>
<option value="156">CAMEROON</option>
<option value="157">CANADA</option>
<option value="158">CANARY ISLANDS</option>
<option value="102">CAPE VERDE</option>
<option value="103">CAYMAN ISLANDS, UNITED KINGDOM</option>
<option value="200">CENTRAL AFRICAN REPUBLIC</option>
<option value="107">CHAD</option>
<option value="228">CHILE</option>
<option value="16">CHINA</option>
<option value="105">CHRISTMAS ISLAND, AUSTRALIA</option>
<option value="40">COLOMBIA</option>
<option value="161">COMOROS</option>
<option value="41">CONGO</option>
<option value="164">COSTA RICA</option>
<option value="25">CROATIA</option>
<option value="43">CUBA</option>
<option value="142">CYPRUS</option>
<option value="108">CZECH REPUBLIC</option>
<option value="162">DEMOCRATIC REPUBLIC OF CONGO</option>
<option value="109">Denmark</option>
<option value="106">DJIBOUTI</option>
<option value="111">DOMINICAN REPUBLIC</option>
<option value="112">Dominica</option>
<option value="110">EAST TIMOR</option>
<option value="113">ECUADOR</option>
<option value="53">EGYPT</option>
<option value="115">EL SALVADOR</option>
<option value="28">ENGLAND</option>
<option value="114">EQUATORIAL GUINEA</option>
<option value="117">ERITREA</option>
<option value="119">ESTONIA</option>
<option value="17">ETHIOPIA</option>
<option value="123">Falkland Islands, British</option>
<option value="120">FIJI</option>
<option value="20">FINLAND</option>
<option value="124">FRANCE</option>
<option value="125">FRENCH GUIANA</option>
<option value="127">FRENCH POLYNESIA</option>
<option value="126">FRENCH SOUTHERN Province (Kerguelen Islands)</option>
<option value="128">GABON</option>
<option value="130">GAMBIA</option>
<option value="23">GEORGIA</option>
<option value="4">GERMANY</option>
<option value="131">GHANA</option>
<option value="104">GIBRALTAR, UNITED KINGDOM</option>
<option value="79">GREECE</option>
<option value="135">GREENLAND</option>
<option value="134">GRENADA</option>
<option value="136">GUADELOUPE, FRANCE</option>
<option value="137">GUAM, AMERICAN</option>
<option value="138">GUATEMALA</option>
<option value="132">GUINEA</option>
<option value="139">GUYANA</option>
<option value="145">HAITI</option>
<option value="147">HONDURAS</option>
<option value="27">HONG KONG</option>
<option value="50">HUNGARY</option>
<option value="151">ICELAND</option>
<option value="24">INDIA</option>
<option value="116">INDONESIA</option>
<option value="30">IRAN</option>
<option value="29">IRAQ</option>
<option value="148">IRELAND</option>
<option value="31">ISRAEL</option>
<option value="33">ITALY</option>
<option value="121">IVORY COAST</option>
<option value="152">JAMAICA</option>
<option value="34">Jamaica</option>
<option value="35">JAPAN</option>
<option value="153">JOHNSTON ATOLL, AMERICA</option>
<option value="239">JORDAN</option>
<option value="38">KAZAKHSTAN</option>
<option value="159">KENYA</option>
<option value="160">KIRIBATI</option>
<option value="163">KOSOVO</option>
<option value="44">KUWAIT</option>
<option value="39">KYRGYZSTAN</option>
<option value="169">LAOS</option>
<option value="170">LATVIA</option>
<option value="49">LEBANON</option>
<option value="46">LESOTHO</option>
<option value="171">LIBERIA</option>
<option value="47">LIBYA</option>
<option value="172">LIECHTENSTEIN</option>
<option value="48">LITHUANIA</option>
<option value="174">LUXEMBOURG</option>
<option value="176">MACAU (Macau)</option>
<option value="51">MACEDONIA</option>
<option value="175">MADAGASCAR</option>
<option value="177">MALAWI</option>
<option value="52">MALAYSIA</option>
<option value="178">Maldive Islands</option>
<option value="179">MALI</option>
<option value="180">MALTA</option>
<option value="181">Marshall Islands</option>
<option value="182">Martinique, FRANCE</option>
<option value="191">MAURITANIA</option>
<option value="183">MAURITIUS</option>
<option value="184">MAYOTTE, FRANCE</option>
<option value="185">MEXICO</option>
<option value="187">MICRONESIA</option>
<option value="186">Midway Islands, U.S.</option>
<option value="55">MOLDOVA</option>
<option value="189">MONACO</option>
<option value="54">MONGOLIA</option>
<option value="36">MONTENEGRO</option>
<option value="190">MONTSERRAT</option>
<option value="18">MOROCCO</option>
<option value="192">MOZAMBIQUE</option>
<option value="95">MYANMAR (BURMA)</option>
<option value="193">Namibia</option>
<option value="194">NAURU</option>
<option value="195">NEPAL</option>
<option value="26">NETHERLANDS</option>
<option value="146">NETHERLANDS ANTILLES</option>
<option value="247">NEW CALEDONIA, FRANCE</option>
<option value="248">NEW ZEALAND</option>
<option value="197">NICARAGUA</option>
<option value="196">NIGER</option>
<option value="56">NIGERIA</option>
<option value="198">NIUE, NEW ZEALAND</option>
<option value="166">NORTH KOREA</option>
<option value="165">NORTHERN IRELAND</option>
<option value="167">NORTHERN Maryana ISLANDS</option>
<option value="199">NORWAY</option>
<option value="133">of Guinea-Bissau</option>
<option value="237">OMAN</option>
<option value="58">PAKISTAN</option>
<option value="201">PALAU ISLANDS</option>
<option value="122">PALESTINE</option>
<option value="202">PALMYRA ATOLL, AMERICA</option>
<option value="203">PANAMA</option>
<option value="204">PAPUA NEW GUINEA</option>
<option value="205">PARAGUAY</option>
<option value="206">PERU</option>
<option value="59">POLAND</option>
<option value="207">PORTUGAL</option>
<option value="208">PUERTO RICO, UNITED STATES</option>
<option value="37">QATAR</option>
<option value="251">REPUBLIC OF SOUTH SUDAN</option>
<option value="209">Réunion, FRANCE</option>
<option value="60">ROMANIA</option>
<option value="62">RUSSIAN FEDERATION</option>
<option value="61">RWANDA</option>
<option value="210">SAINT HELENA, ENGLAND</option>
<option value="211">Saint Martin, France</option>
<option value="212">Saint Pierre And Miquelon, FRANCE</option>
<option value="213">SAMOA</option>
<option value="214">SAN MARINO</option>
<option value="215">SANTA Kitts and Nevis</option>
<option value="216">SANTA LUCIA</option>
<option value="217">SANTA Vincent and the Grenadines</option>
<option value="218">São Tomé and Príncipe</option>
<option value="69">SAUDI ARABIA</option>
<option value="219">SENEGAL</option>
<option value="64">SERBIA</option>
<option value="220">SEYCHELLES</option>
<option value="221">SIERRA LEONE</option>
<option value="63">SINGAPORE</option>
<option value="65">SLOVAKIA</option>
<option value="66">SLOVENIA</option>
<option value="222">SOLOMON ISLANDS</option>
<option value="223">SOMALIA</option>
<option value="21">SOUTH AFRICA</option>
<option value="141">SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS, ENGLAND</option>
<option value="22">SOUTH KOREA</option>
<option value="149">SPAIN</option>
<option value="224">SRI LANKA</option>
<option value="67">SUDAN</option>
<option value="225">SURINAME</option>
<option value="226">SVALBARD, NORWAY</option>
<option value="227">SWAZILAND</option>
<option value="32">SWEDEN</option>
<option value="150">SWITZERLAND</option>
<option value="68">SYRIA</option>
<option value="73">TAIWAN</option>
<option value="70">TAJIKISTAN</option>
<option value="229">TANZANIA</option>
<option value="71">TATARİSTAN</option>
<option value="72">THAILAND</option>
<option value="42">THE DEMOCRATIC PEOPLES REPUBLIC OF KOREA</option>
<option value="19">THE PHILIPPINES</option>
<option value="230">TOGO</option>
<option value="231">TONGA</option>
<option value="232">TRINIDAD AND TOBAGO</option>
<option value="74">TUNISIA</option>
<option value="45">TURKISH REPUBLIC OF NORTHERN CYPRUS</option>
<option value="75">TURKMENISTAN</option>
<option value="1">TÜRKİYE</option>
<option value="233">Turks and Caicos Islands, England</option>
<option value="234">TUVALU</option>
<option value="76">UGANDA</option>
<option value="77">UKRAINE</option>
<option value="12">UNITED ARAB EMIRATES</option>
<option value="2">UNITED STATES OF AMERICA</option>
<option value="238">URUGUAY</option>
<option value="57">UZBEKISTAN</option>
<option value="240">Vallis and Futuna, FRANCE</option>
<option value="241">VANUATU</option>
<option value="242">VENEZUELA</option>
<option value="243">VIETNAM</option>
<option value="244">VIRGIN ISLANDS, UNITED STATES</option>
<option value="245">Virgin Islands, British</option>
<option value="246">WAKE ISLAND, AMERICA</option>
<option value="129">WALES</option>
<option value="78">YEMEN</option>
<option value="249">ZAMBIA</option>
<option value="250">ZIMBABWE</option>
</select>